clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /promtail_pos/positions.yaml

scrape_configs:
  - job_name: demo
    static_configs:
    - targets:
      - localhost
      labels:
        job: varlogs
        __path__: /var/log/*.log
    - targets:
      - localhost
      labels:
        job: demo
        __path__: /app/logs/*.log
